import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '../globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {

	return (
		<html lang={ 'ru' }>
		<body>
			{ children }
		</body>
		</html>
	);
}
