import type { Metadata } from 'next';
import '../globals.css';
import { notFound } from 'next/navigation';
import { hasLocale } from 'use-intl';
import { routing } from '@/i18n/routing';
import { NextIntlClientProvider } from 'next-intl';
import { Inter, Roboto } from 'next/font/google'

const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	display: 'swap',
	variable: '--font-inter'
})

const roboto = Roboto({
	subsets: ['latin', 'cyrillic'],
	display: 'swap',
	variable: '--font-roboto'
})


export const metadata: Metadata = {
	title: 'Farbio',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: LayoutProps<'/[locale]'>) {
	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	return (
		<html lang={ locale }>
		<body className={`${inter.className} ${roboto.className}`}>
		<NextIntlClientProvider>
			{ children }
		</NextIntlClientProvider>
		</body>
		</html>
	);
}
